---
default:
    db:
      port: "5432"
      database: "picking"

development:
    db:
      host: "galwat-remote.ydns.eu"
    inventory-service:
      host: "galwat-remote.ydns.eu/inventory"
    common-service:
      host: "galwat-remote.ydns.eu/common"

production:
    db:
      host: "postgres"
    inventory-service:
      host: "inventory"
    common-service:
      host: "common"
