services:
  topology-migrations:
    container_name: topology-migrations
    build: ./topology
    depends_on:
      - postgres
    command:
      - "dbmate"
      - "--url"
      - "postgres://${PG_USER}:${PG_PASSWORD}@${PG_DEFAULT_DB}:${PG_PORT}/topology?sslmode=disable"
      - "up"
  
  topology:
    container_name: topology
    build: ./topology
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - topology-migrations