services:
  common-migrations:
    container_name: common-migrations
    build: ./common
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - "dbmate"
      - "--url"
      - "postgres://${PG_USER}:${PG_PASSWORD}@${PG_DEFAULT_DB}:${PG_PORT}/common?sslmode=disable"
      - "up"
  
  common:
    container_name: common
    build: ./common
    ports:
      - 80:80
    depends_on:
      common-migrations:
        condition: service_completed_successfully